name: pilar_mobile_challenge
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.1
  flutter_mobx: ^2.2.0+2

  dartz: ^0.10.1
  mobx: ^2.3.0+1
  get_it: ^7.6.7
  freezed_annotation: ^2.4.1
  cached_network_image: ^3.3.1
  mockito: ^5.4.4
  equatable: ^2.0.5
  google_fonts: ^6.2.0
  curved_progress_bar: ^1.0.2
  intl: ^0.19.0
  palette_generator: ^0.3.3+3
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mobx_codegen: ^2.6.0+1
  freezed: ^2.4.7
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  integration_test:
    sdk: flutter
  patrol: ^3.5.2

flutter:
  uses-material-design: true

patrol:
  app_name: My App
  android:
    package_name: com.example.pilar_mobile_challenge
  ios:
    bundle_id: com.example.pilarMobileChallenge
